version: '3.8'

services:
  db:
    image: postgres:15
    container_name: development
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    ports:
      - '25432:5432'
