name: auto-cd(dev)

on:
  workflow_dispatch:
    inputs:
      dev_command:
        type: choice
        required: true
        description: 'dev command'
        options:
          - yarn dev
          - yarn dev:test

env:
  SERVER_HOST: ${{ secrets.DEV_SERVER_HOST }}
  SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}
  DEPLOY_PATH: /choose-tale/Backend
  BRANCH: ${{github.ref_name}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo env
        run: |
          echo ${{ env.DEPLOY_PATH }}
          echo ${{ env.BRANCH }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          

      - name: SSH into server and execute commands
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{env.SERVER_USER}}@${{ env.SERVER_HOST }}

      - name: 원격 서버에 배포
        run: |
          scp -r ./* ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.DEPLOY_PATH }}
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << EOF
          cd ${{ env.DEPLOY_PATH }}
          git fetch --all
          git switch ${{ env.BRANCH }}
          git pull origin ${{ env.BRANCH }}
          yarn
          nohup ${{inputs.dev_command}} > /dev/null 2>&1 &
          EOF

      - name: SSH 키 정리
        run: rm -rf ~/.ssh
