name: auto-cd(dev)

on:
  workflow_dispatch:
    inputs:
      dev_command:
        type: choice
        required: true
        description: 'dev command'
        options:
          - yarn dev
          - yarn dev:test

env:
  SERVER_HOST: ${{ secrets.DEV_SERVER_HOST }}
  SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}
  SERVER_SSH_PASSPHRASE: ${{ secrets.DEV_SERVER_SSH_PASSPHRASE }}
  DEPLOY_PATH: choose-tale/Backend
  BRANCH: ${{github.ref_name}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo env
        run: |
          echo ${{ env.DEPLOY_PATH }}
          echo ${{ env.BRANCH }}

      - name: Set up SSH key with passphrase
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.SERVER_SSH_KEY }}
          ssh-passphrase: ${{ env.SERVER_SSH_PASSPHRASE }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 원격 서버에 배포
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF'
          pwd
          ls
          cd ${{ env.DEPLOY_PATH }}
          git fetch --all
          git pull origin ${{ env.BRANCH }}
          yarn install --frozen-lockfile
          ${{ inputs.dev_command }}
          EOF

      - name: SSH 키 정리
        run: rm -rf ~/.ssh
